#ifndef LORA_CONTRACTS_H
#define LORA_CONTRACTS_H

#ifdef __cplusplus
extern "C" {
#endif

#define LORA_CMD_AUTO "AUTO"
#define LORA_CMD_MANUAL "MANUAL"
#define LORA_CMD_PAUSE "PAUSE"
#define LORA_CMD_ESTOP "ESTOP"
#define LORA_CMD_STOP "STOP"
#define LORA_CMD_RESET "RESET"

#define LORA_WP_CLEAR "WPCLEAR"
#define LORA_WP_CLEAR_ALIAS "WC"
#define LORA_WP_ADD_PREFIX "WP"
#define LORA_WP_ADD_ALIAS_PREFIX "W"
#define LORA_WP_BATCH_PREFIX "WPB"
#define LORA_WP_BATCH_ALIAS_PREFIX "WB"
#define LORA_WP_LOAD_PREFIX "WPLOAD"
#define LORA_WP_LOAD_ALIAS_PREFIX "WL"

#define LORA_WP_ACK_CLEAR "ACK:WPCLEAR"
#define LORA_WP_ACK_ADD_PREFIX "ACK:WP"
#define LORA_WP_ACK_BATCH_PREFIX "ACK:WPB"
#define LORA_WP_ACK_LOAD_PREFIX "ACK:WPLOAD"

#ifdef __cplusplus
}
#endif

#endif